### ISSUE TITLE
 customize background color for sections 

### ISSUE THREAD

**Issue by jamalalayq** [johntvolk/ExpandableColumnLayout#5]
set features to set and customize background color or image and insets and corner radius  for every section

**Comment by johntvolk** [comment]
Thanks for the feedback.

Are you trying to customize the UICollectionReusableView returned for ExpandableColumnLayoutSectionBackgroundKind? If so, you can do this by implementing:

`public func collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionReusableView`

If that's not what you're trying to do, please provide a few more details. Thanks!

**Comment by jamalalayq** [comment]
i try to set background color for evey section, but sections background take collection view background color

**Comment by johntvolk** [comment]
I think I see what's happening. You're probably inheriting from `ExpandableColumnViewController` in your controller. `ExpandableColumnViewController` comes with an implementation of `collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath)` that sets the background color of each `ExpandableColumnLayoutSectionBackgroundKind` to the color of the collection view. See [here](https://github.com/johntvolk/ExpandableColumnLayout/blob/master/Pod/Classes/ExpandableColumnViewController.swift#L60).

If you want different behavior, you either need to not inherit from `ExpandableColumnViewController` (which requires implementing `ExpandableColumnLayoutDelegate`). Or, you need to override it's implementation of `collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath)` in your controller to insert your preferred behavior.

Does that help?
